---
# tasks file for postgresql_install

  - block:
    - name: install required pgsql repository for {{ pgsql_version }}
      yum:
        name: "{{ pgsql_repo }}"
        state: installed

    - name: install postgresql database packages {{ pgsql_version }}
      yum:
        name: "{{ pgsql_packages }}"
        state: installed


