---
# tasks file for postgresql_install

  - block:
    - name: install required pgsql repository for {{ pgsql_version }}
      yum:
        name: "{{ pgsql_repo }}"
        state: installed

    - name: install postgresql database packages {{ pgsql_version }}
      yum:
        name: "{{ pgsql_packages }}"
        state: installed

    - name: initialize the database {{ pgsql_version }}
      command: '{{ pgsql_initdb }}'
      args:
        creates: /var/lib/pgsql/9.6/data/
      notify: start the database {{ pgsql_version }}
